version: "3.8"

# Определяются три сервиса: 
# api - основное приложение, 
# базы данных: redis и postgres.
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    command: [
      "uvicorn", "app.main:app",
      "--host", "0.0.0.0",
      "--port", "8000"
    ]
    
  redis:
    container_name: redis
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    env_file:
      - .env
    hostname: redis
    ports:
      - 6379:6379
  
  postgres:
    container_name: postgres
    hostname: postgres
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    env_file:
      - .env
    ports:
      - 5432:5432

# Секция определяет внешнюю сеть с именем app_main
# Она позволяет нескольким контейнерам связываться друг с другом, а также с внешними ресурсами.
networks:
  default:
    external: true
    name: app_main